"""Shared write primitives for every runtime target.

Installing must be idempotent and reversible: removing an entry from `state.yml`
has to remove it from the runtime too. Runtime config files are shared with the
user and with other tools, so Mires never rewrites them wholesale. Instead every
install records what it wrote in a manifest under the target home, and the next
install prunes exactly what the previous one owned before writing the new set.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = [
    "GENERATED_NOTICE",
    "InstallManifest",
    "clear_managed_markdown",
    "copy_generated_tree",
    "install_hook_scripts",
    "managed_markdown_block",
    "read_json_object",
    "write_json_object",
    "write_managed_markdown",
]

GENERATED_NOTICE = "Generated by Mires. Edit the Mires repository and run the installer again."
BLOCK_BEGIN = "<!-- BEGIN MIRES -->"
BLOCK_END = "<!-- END MIRES -->"
MANIFEST_RELATIVE = Path("mires") / "install-manifest.json"
MANIFEST_VERSION = 1


@dataclass
class InstallManifest:
    """Record of everything the previous install owned inside a target home."""

    home: Path
    paths: list[str] = field(default_factory=list)
    keys: dict[str, list[str]] = field(default_factory=dict)

    @classmethod
    def load(cls, home: Path) -> InstallManifest:
        path = home / MANIFEST_RELATIVE
        if not path.exists():
            return cls(home=home)
        try:
            document = json.loads(path.read_text())
        except json.JSONDecodeError:
            return cls(home=home)
        if not isinstance(document, dict) or document.get("version") != MANIFEST_VERSION:
            return cls(home=home)
        return cls(
            home=home,
            paths=[item for item in document.get("paths", []) if isinstance(item, str)],
            keys={
                str(scope): [key for key in owned if isinstance(key, str)]
                for scope, owned in (document.get("keys") or {}).items()
                if isinstance(owned, list)
            },
        )

    def owned_keys(self, scope: str) -> list[str]:
        return self.keys.get(scope, [])

    def track_path(self, path: Path) -> None:
        self.paths.append(str(path.relative_to(self.home)))

    def track_keys(self, scope: str, keys: list[str]) -> None:
        self.keys[scope] = sorted(keys)

    def prune_stale_paths(self, previous: InstallManifest) -> None:
        """Delete anything the previous install created that this one no longer produces."""
        current = set(self.paths)
        for relative in sorted(set(previous.paths) - current, reverse=True):
            stale = self.home / relative
            if stale.is_dir():
                shutil.rmtree(stale, ignore_errors=True)
            elif stale.exists():
                stale.unlink()

    def save(self) -> None:
        path = self.home / MANIFEST_RELATIVE
        path.parent.mkdir(parents=True, exist_ok=True)
        document = {
            "version": MANIFEST_VERSION,
            "notice": GENERATED_NOTICE,
            "paths": sorted(set(self.paths)),
            "keys": {scope: sorted(set(keys)) for scope, keys in sorted(self.keys.items())},
        }
        path.write_text(json.dumps(document, indent=2) + "\n")


def copy_generated_tree(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source_path in sorted(source.rglob("*")):
        relative_path = source_path.relative_to(source)
        if any(part == "__pycache__" for part in relative_path.parts) or source_path.suffix == ".pyc":
            continue
        destination_path = destination / relative_path
        if source_path.is_dir():
            destination_path.mkdir(parents=True, exist_ok=True)
            continue
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)


def install_hook_scripts(home: Path, hooks: Any, manifest: InstallManifest | None = None) -> dict[str, Path]:
    """Copy each hook's directory into the target home so the install stops depending on the repository path.

    Returns the installed directory per hook name.
    """
    installed: dict[str, Path] = {}
    for hook in hooks:
        destination = home / "mires" / "hooks" / hook.name
        copy_generated_tree(hook.directory, destination)
        for script in destination.rglob("*"):
            if script.is_file() and script.suffix in {".sh", ".bash", ".py"}:
                script.chmod(script.stat().st_mode | 0o111)
        if manifest is not None:
            manifest.track_path(destination)
        installed[hook.name] = destination
    return installed


def managed_markdown_block(body: str) -> str:
    return f"{BLOCK_BEGIN}\n{body.strip()}\n{BLOCK_END}"


def write_managed_markdown(path: Path, body: str) -> None:
    """Replace the Mires block in a shared Markdown file, preserving the user's own prose.

    An empty body removes the block entirely so dropping every rule from the catalog
    is reversible, the same way path and key pruning reverse other asset kinds.
    """
    if not body.strip():
        clear_managed_markdown(path)
        return
    block = managed_markdown_block(body)
    existing = path.read_text() if path.exists() else ""
    before, _, remainder = existing.partition(BLOCK_BEGIN)
    if remainder:
        _, _, after = remainder.partition(BLOCK_END)
        merged = f"{before.rstrip()}\n\n{block}\n{after.lstrip()}".strip()
    else:
        merged = f"{existing.rstrip()}\n\n{block}".strip()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(merged + "\n")


def clear_managed_markdown(path: Path) -> None:
    """Remove the Mires block from a shared Markdown file, leaving the user's prose."""
    if not path.exists():
        return
    existing = path.read_text()
    before, found, remainder = existing.partition(BLOCK_BEGIN)
    if not found:
        return
    _, _, after = remainder.partition(BLOCK_END)
    merged = f"{before.rstrip()}\n{after.lstrip()}".strip()
    if merged:
        path.write_text(merged + "\n")
    else:
        path.unlink()


def read_json_object(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        document = json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}
    return document if isinstance(document, dict) else {}


def write_json_object(path: Path, document: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(document, indent=2) + "\n")
