from __future__ import annotations

from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))

from compatibility.models import AgentAsset, SkillAsset  # noqa: E402
from compatibility.opencode import render_agent_markdown, render_skill_markdown  # noqa: E402
from compatibility.parsing import read_frontmatter  # noqa: E402


def make_agent(name: str = "backend") -> AgentAsset:
    return AgentAsset(
        name=name,
        description=f"{name} canonical description",
        parent="orchestrator",
        children=("tester",) if name == "backend" else (),
        path=ROOT / ".ai" / "agents" / name / "AGENT.md",
        metadata_path=ROOT / ".ai" / "agents" / name / "agents" / "openai.yaml",
        metadata={
            "interface": {
                "display_name": name.title(),
                "short_description": f"{name} short description",
                "default_prompt": f'Use ${name}. Keep "quotes" valid.',
            },
            "metadata": {
                "name": name,
                "parent": "orchestrator",
                "children": ["tester"] if name == "backend" else [],
            },
        },
    )


def make_skill(name: str = "python") -> SkillAsset:
    return SkillAsset(
        name=name,
        description=f"{name} skill description",
        path=ROOT / ".ai" / "skills" / name / "SKILL.md",
        reference_paths=(),
    )


def read_generated_frontmatter(text: str) -> dict[str, object]:
    with tempfile.TemporaryDirectory() as temp_dir:
        path = Path(temp_dir) / "generated.md"
        path.write_text(text)
        return read_frontmatter(path)


class OpenCodeAgentRenderingTests(unittest.TestCase):
    def test_render_agent_markdown_is_valid_opencode_agent(self) -> None:
        rendered = render_agent_markdown(make_agent(), (), Path("/tmp/mires-opencode-home"))
        frontmatter = read_generated_frontmatter(rendered)

        self.assertEqual(frontmatter["description"], "backend short description")
        self.assertEqual(frontmatter["mode"], "subagent")
        self.assertIn('Keep "quotes" valid.', rendered)
        self.assertNotIn("Use $backend.", rendered)
        self.assertIn("/tmp/mires-opencode-home/mires/agents/backend/AGENT.md", rendered)
        self.assertNotIn(".ai/", rendered)

    def test_render_orchestrator_as_primary_agent(self) -> None:
        rendered = render_agent_markdown(make_agent("orchestrator"), (), Path("/tmp/mires-opencode-home"))
        frontmatter = read_generated_frontmatter(rendered)

        self.assertEqual(frontmatter["mode"], "primary")


class OpenCodeSkillRenderingTests(unittest.TestCase):
    def test_render_skill_markdown_is_valid_opencode_skill(self) -> None:
        rendered = render_skill_markdown(make_skill())
        frontmatter = read_generated_frontmatter(rendered)

        self.assertEqual(frontmatter["name"], "python")
        self.assertIn("description", frontmatter)
        self.assertIn("Generated by Mires for OpenCode", rendered)
        self.assertNotIn(".ai/", rendered)


class OpenCodeInstallCommandTests(unittest.TestCase):
    def test_install_command_writes_agents_skills_and_bundles_to_alternate_opencode_home(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            opencode_home = Path(temp_dir) / ".config" / "opencode"
            result = subprocess.run(
                [
                    sys.executable,
                    str(SRC / "main.py"),
                    "install",
                    "--target",
                    "opencode",
                    "--root",
                    str(ROOT),
                    "--opencode-home",
                    str(opencode_home),
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Installed 8 OpenCode agents", result.stdout)
            self.assertTrue((opencode_home / "agents" / "backend.md").exists())
            self.assertTrue((opencode_home / "mires" / "agents" / "backend" / "AGENT.md").exists())
            self.assertTrue((opencode_home / "skills" / "python" / "SKILL.md").exists())
            generated_text = "\n".join(
                path.read_text()
                for path in opencode_home.rglob("*")
                if path.is_file() and path.suffix in {".md", ".yaml", ".yml", ".toml"}
            )
            self.assertNotIn(".ai/", generated_text)

    def test_dry_run_does_not_write_to_alternate_opencode_home(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            opencode_home = Path(temp_dir) / ".config" / "opencode"
            result = subprocess.run(
                [
                    sys.executable,
                    str(SRC / "main.py"),
                    "install",
                    "--target",
                    "opencode",
                    "--root",
                    str(ROOT),
                    "--opencode-home",
                    str(opencode_home),
                    "--dry-run",
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Dry run: would install 8 OpenCode agents", result.stdout)
            self.assertFalse(opencode_home.exists())


class CompatibilityTargetDispatchTests(unittest.TestCase):
    def test_codex_check_still_works(self) -> None:
        result = subprocess.run(
            [sys.executable, str(SRC / "main.py"), "--target", "codex", "--root", str(ROOT)],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Compatibility check passed for target 'codex'", result.stdout)

    def test_unsupported_target_fails_clearly(self) -> None:
        result = subprocess.run(
            [sys.executable, str(SRC / "main.py"), "--target", "unsupported-runtime", "--root", str(ROOT)],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

        self.assertEqual(result.returncode, 2)
        self.assertIn("unsupported compatibility target", result.stderr)


if __name__ == "__main__":
    unittest.main()
