from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from mires.compatibility.models import AgentAsset, SkillAsset
from mires.compatibility.opencode import install_opencode_assets, render_agent_markdown, render_skill_markdown
from mires.compatibility.parsing import filter_inventory, load_inventory
from mires.frontmatter import parse_frontmatter
from mires.state import load_state

ROOT = Path(__file__).resolve().parents[3]
CLI = ["-m", "mires.cli"]


def make_agent(name: str = "planner") -> AgentAsset:
    return AgentAsset(
        name=name,
        description=f"{name} canonical description",
        parent="",
        children=(),
        path=ROOT / "subagents" / name / "AGENT.md",
        metadata_path=ROOT / "subagents" / name / "agents" / "openai.yaml",
        metadata={
            "interface": {
                "display_name": name.title(),
                "short_description": f"{name} short description",
                "default_prompt": f'Use ${name}. Keep "quotes" valid.',
            },
            "metadata": {"name": name, "parent": "", "children": []},
        },
    )


def make_skill(name: str = "mires-python") -> SkillAsset:
    return SkillAsset(
        name=name,
        description=f"{name} skill description",
        path=ROOT / "skills" / name / "SKILL.md",
        reference_paths=(),
    )


def run_cli(*arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, *CLI, *arguments],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


class OpenCodeAgentRenderingTests(unittest.TestCase):
    def test_render_agent_markdown_is_valid_opencode_agent(self) -> None:
        rendered = render_agent_markdown(make_agent(), (), Path("/tmp/mires-opencode-home"))
        frontmatter = parse_frontmatter(rendered)

        self.assertEqual(frontmatter["description"], "planner short description")
        self.assertEqual(frontmatter["mode"], "subagent")
        self.assertIn('Keep "quotes" valid.', rendered)
        self.assertNotIn("Use $planner.", rendered)
        self.assertIn("/tmp/mires-opencode-home/mires/agents/planner/AGENT.md", rendered)
        self.assertNotIn("subagents/", rendered)

    def test_render_explorer_as_primary_agent(self) -> None:
        rendered = render_agent_markdown(make_agent("explorer"), (), Path("/tmp/mires-opencode-home"))
        frontmatter = parse_frontmatter(rendered)

        self.assertEqual(frontmatter["mode"], "primary")


class OpenCodeSkillRenderingTests(unittest.TestCase):
    def test_render_skill_markdown_is_valid_opencode_skill(self) -> None:
        rendered = render_skill_markdown(make_skill())
        frontmatter = parse_frontmatter(rendered)

        self.assertEqual(frontmatter["name"], "mires-python")
        self.assertIn("description", frontmatter)
        self.assertIn("Generated by Mires for OpenCode", rendered)


def install(home: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    return run_cli("install", "--target", "opencode", "--root", str(ROOT), "--opencode-home", str(home), *extra)


class OpenCodeInstallCommandTests(unittest.TestCase):
    def test_install_command_writes_agents_skills_and_bundles(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            opencode_home = Path(temp_dir) / ".config" / "opencode"
            result = install(opencode_home)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Installed 2 subagents", result.stdout)
            self.assertTrue((opencode_home / "agents" / "planner.md").exists())
            self.assertTrue((opencode_home / "mires" / "agents" / "planner" / "AGENT.md").exists())
            self.assertTrue((opencode_home / "skills" / "mires-python" / "SKILL.md").exists())
            self.assertTrue((opencode_home / "AGENTS.md").exists())
            self.assertIn("context7", json.loads((opencode_home / "opencode.json").read_text())["mcp"])
            self.assertIn("has no runtime for: hooks", result.stdout)

    def test_profile_narrows_the_installed_skill_packages(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            opencode_home = Path(temp_dir) / ".config" / "opencode"
            install(opencode_home)
            result = install(opencode_home, "--profile", "tenant-evaluation")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((opencode_home / "skills" / "mires-django").exists())
            self.assertFalse((opencode_home / "skills" / "mires-react").exists())
            rules = (opencode_home / "AGENTS.md").read_text()
            self.assertIn("No Secrets", rules)
            self.assertNotIn("Commit Style", rules)

    def test_clearing_every_rule_removes_the_managed_agents_block(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            home = Path(temp_dir) / ".config" / "opencode"
            home.mkdir(parents=True)
            (home / "AGENTS.md").write_text("# Mine\n\nKeep me.\n")
            inventory = load_inventory(ROOT, load_state(ROOT))
            install_opencode_assets(inventory, home)

            cleared = filter_inventory(
                inventory,
                agent_names={agent.name for agent in inventory.agents},
                skill_names={skill.name for skill in inventory.skills},
                rule_names=set(),
                mcp_names={mcp.name for mcp in inventory.mcps},
                hook_names=set(),
            )
            install_opencode_assets(cleared, home)
            text = (home / "AGENTS.md").read_text()

            self.assertIn("Keep me.", text)
            self.assertNotIn("<!-- BEGIN MIRES -->", text)

    def test_dry_run_does_not_write_to_alternate_opencode_home(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            opencode_home = Path(temp_dir) / ".config" / "opencode"
            result = install(opencode_home, "--dry-run")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Dry run: would install the Mires catalog", result.stdout)
            self.assertFalse(opencode_home.exists())


class CompatibilityTargetDispatchTests(unittest.TestCase):
    def test_codex_check_still_works(self) -> None:
        result = run_cli("--target", "codex", "--root", str(ROOT))

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("Compatibility check passed for target 'codex'", result.stdout)

    def test_unsupported_target_fails_clearly(self) -> None:
        result = run_cli("--target", "unsupported-runtime", "--root", str(ROOT))

        self.assertEqual(result.returncode, 2)
        self.assertIn("unsupported target: unsupported-runtime", result.stderr)


if __name__ == "__main__":
    unittest.main()
