from __future__ import annotations

from pathlib import Path
import re
import shutil
import textwrap
import tomllib
from typing import Any

from compatibility.models import AgentAsset, AssetInventory, SkillAsset, ValidationMessage


SUPPORTED_TARGET = "codex"
CONFIG_FILE = "config.toml"
AGENTS_DIR = "agents"
MIRES_DIR = "mires"
PROMPT_WRAP_WIDTH = 131


def validate_codex(inventory: AssetInventory) -> tuple[ValidationMessage, ...]:
    errors: list[ValidationMessage] = list(inventory.errors)
    for agent in inventory.agents:
        metadata_path = agent.metadata_path or agent.path.parent / "agents" / "openai.yaml"
        metadata = agent.metadata
        interface = _mapping(metadata.get("interface"))
        runtime_metadata = _mapping(metadata.get("metadata"))

        _require_string(interface, "display_name", metadata_path, errors)
        _require_string(interface, "short_description", metadata_path, errors)
        _require_string(interface, "default_prompt", metadata_path, errors)
        codex_name = _require_string(runtime_metadata, "name", metadata_path, errors)
        if codex_name and codex_name != agent.name:
            errors.append(
                ValidationMessage(
                    metadata_path,
                    f"metadata.name must match agent front matter name: {agent.name}",
                )
            )

        children = runtime_metadata.get("children")
        if children is not None and not (
            isinstance(children, list) and all(isinstance(child, str) for child in children)
        ):
            errors.append(ValidationMessage(metadata_path, "metadata.children must be a list of strings"))

    return tuple(errors)


def check_target_supported(target: str, path: Path) -> tuple[ValidationMessage, ...]:
    if target == SUPPORTED_TARGET:
        return ()
    return (ValidationMessage(path, f"unsupported compatibility target: {target}"),)


def install_codex_agents(inventory: AssetInventory, codex_home: Path, dry_run: bool = False) -> int:
    agents = tuple(sorted(inventory.agents, key=lambda agent: agent.name))
    skills_by_name = {skill.name: skill for skill in inventory.skills}
    bundle_plans = tuple((agent, referenced_skills(agent, skills_by_name)) for agent in agents)
    rendered_agents = tuple((agent, render_agent_toml(agent, skills, codex_home)) for agent, skills in bundle_plans)
    config_path = codex_home / CONFIG_FILE
    existing_config = config_path.read_text() if config_path.exists() else ""
    patched_config = patch_agents_config(existing_config, agents)
    validate_install_output(rendered_agents, bundle_plans, patched_config)

    if dry_run:
        print(f"Dry run: would install {len(rendered_agents)} Codex agents into {codex_home}")
        for agent, skills in bundle_plans:
            print(f"- would write {agent_file_path(codex_home, agent)}")
            print(f"- would refresh {agent_bundle_path(codex_home, agent)}")
            for skill in skills:
                print(f"  - would bundle skill {skill.name}")
        print(f"- would update {config_path}")
        return len(rendered_agents)

    agents_dir = codex_home / AGENTS_DIR
    agents_dir.mkdir(parents=True, exist_ok=True)
    remove_legacy_agent_bundle_root(codex_home)
    for agent, content in rendered_agents:
        agent_file_path(codex_home, agent).write_text(content)
    for agent, skills in bundle_plans:
        write_agent_bundle(codex_home, agent, skills)

    codex_home.mkdir(parents=True, exist_ok=True)
    config_path.write_text(patched_config)
    return len(rendered_agents)


def agent_file_path(codex_home: Path, agent: AgentAsset) -> Path:
    return codex_home / AGENTS_DIR / f"{agent.name}.toml"


def agent_bundle_path(codex_home: Path, agent: AgentAsset) -> Path:
    return codex_home / MIRES_DIR / AGENTS_DIR / agent.name


def remove_legacy_agent_bundle_root(codex_home: Path) -> None:
    legacy_path = codex_home / AGENTS_DIR / MIRES_DIR
    if legacy_path.exists():
        shutil.rmtree(legacy_path)


def render_agent_toml(
    agent: AgentAsset,
    skills: tuple[SkillAsset, ...] = (),
    codex_home: Path | None = None,
) -> str:
    codex_home = (codex_home or Path.home() / ".codex").expanduser().resolve()
    interface = _mapping(agent.metadata.get("interface"))
    base_prompt = normalize_default_prompt(_string_value(interface.get("default_prompt")) or agent.description, agent)
    instructions = render_developer_instructions(codex_home, agent, skills, base_prompt)

    lines = [
        "# Generated by Mires. Edit the canonical .ai agent source instead.",
        f'developer_instructions = """\n{_toml_multiline_escape(instructions)}\n"""',
    ]
    for skill in skills:
        lines.extend(
            [
                "",
                "[[skills.config]]",
                f'path = "{_toml_escape(str(agent_bundle_path(codex_home, agent) / "skills" / skill.name))}"',
                "enabled = true",
            ]
        )
    return "\n".join(lines) + "\n"


def render_developer_instructions(
    codex_home: Path,
    agent: AgentAsset,
    skills: tuple[SkillAsset, ...],
    base_prompt: str,
) -> str:
    bundle_path = str(agent_bundle_path(codex_home, agent))
    skill_lines = (
        "\n".join(f"- {bundle_path}/skills/{skill.name}" for skill in skills)
        if skills
        else "- No bundled skill packages are required for this agent."
    )
    prompt = f"""
You are the Mires {agent.name} agent.

Primary behavior:
{base_prompt}

Use the bundled agent instructions as the authoritative role guide:
{bundle_path}/AGENT.md

Work from the repository's existing conventions before introducing new patterns. Keep changes scoped to the delegated task and
report blockers, risks, and validation results clearly.

Load bundled skills only when they are relevant to the current task. Do not treat the bundled skills as global session context.
Available bundled skill packages:
{skill_lines}

The bundle is generated from the canonical Mires repository. Do not edit generated files directly; update the canonical .ai source
and run the installer again.
"""
    return wrap_prompt(prompt.strip())


def referenced_skills(agent: AgentAsset, skills_by_name: dict[str, SkillAsset]) -> tuple[SkillAsset, ...]:
    text = agent.path.read_text()
    names = sorted(set(re.findall(r"`skills/([a-z0-9-]+)`", text)))
    return tuple(skills_by_name[name] for name in names if name in skills_by_name)


def write_agent_bundle(codex_home: Path, agent: AgentAsset, skills: tuple[SkillAsset, ...]) -> None:
    bundle_path = agent_bundle_path(codex_home, agent)
    if bundle_path.exists():
        shutil.rmtree(bundle_path)
    bundle_path.mkdir(parents=True, exist_ok=True)

    copy_generated_tree(agent.path.parent, bundle_path)
    skills_path = bundle_path / "skills"
    for skill in skills:
        copy_generated_tree(skill.path.parent, skills_path / skill.name)
    write_bundle_manifest(bundle_path, agent, skills)


def copy_generated_tree(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for source_path in sorted(source.rglob("*")):
        relative_path = source_path.relative_to(source)
        if any(part == "__pycache__" for part in relative_path.parts) or source_path.suffix == ".pyc":
            continue
        destination_path = destination / relative_path
        if source_path.is_dir():
            destination_path.mkdir(parents=True, exist_ok=True)
            continue
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        if source_path.suffix in {".md", ".yaml", ".yml", ".toml"}:
            destination_path.write_text(rewrite_bundle_references(source_path.read_text()))
        else:
            shutil.copy2(source_path, destination_path)


def rewrite_bundle_references(text: str) -> str:
    return text.replace(".ai/skills/", "skills/").replace(".ai/agents/", "agents/")


def write_bundle_manifest(bundle_path: Path, agent: AgentAsset, skills: tuple[SkillAsset, ...]) -> None:
    lines = [
        "# Generated by Mires",
        "",
        f"- Agent: {agent.name}",
        f"- Skills: {', '.join(skill.name for skill in skills) if skills else 'none'}",
    ]
    (bundle_path / "MANIFEST.md").write_text("\n".join(lines) + "\n")


def validate_install_output(
    rendered_agents: tuple[tuple[AgentAsset, str], ...],
    bundle_plans: tuple[tuple[AgentAsset, tuple[SkillAsset, ...]], ...],
    config_text: str,
) -> None:
    for agent, content in rendered_agents:
        try:
            parsed = tomllib.loads(content)
        except tomllib.TOMLDecodeError as exc:
            raise ValueError(f"generated Codex agent TOML is invalid for {agent.name}: {exc}") from exc
        if ".ai/" in content:
            raise ValueError(f"generated Codex agent TOML contains repository-local .ai path for {agent.name}")
        unexpected = set(parsed) - {"developer_instructions", "agent_role", "skills"}
        if unexpected:
            raise ValueError(f"generated Codex agent TOML has unsupported keys for {agent.name}: {sorted(unexpected)}")
    for agent, skills in bundle_plans:
        if not agent.path.exists():
            raise ValueError(f"missing source agent file for {agent.name}: {agent.path}")
        if agent.metadata_path is None or not agent.metadata_path.exists():
            raise ValueError(f"missing source metadata file for {agent.name}")
        for skill in skills:
            if not skill.path.exists():
                raise ValueError(f"missing source skill file for {agent.name}: {skill.path}")
    try:
        tomllib.loads(config_text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"patched Codex config TOML is invalid: {exc}") from exc


def patch_agents_config(config_text: str, agents: tuple[AgentAsset, ...]) -> str:
    normalized = config_text.rstrip()
    blocks = [_agent_registration_block(agent) for agent in sorted(agents, key=lambda item: item.name)]
    without_managed = normalized
    for agent in agents:
        without_managed = _remove_table(without_managed, f"agents.{agent.name}")

    if _has_table(without_managed, "agents"):
        patched = without_managed.rstrip()
    else:
        patched = without_managed.rstrip()
        if patched:
            patched += "\n\n"
        patched += "[agents]"

    if blocks:
        patched = patched.rstrip() + "\n\n" + "\n\n".join(blocks)
    return patched.rstrip() + "\n"


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _string_value(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


def _require_string(
    data: dict[str, Any],
    key: str,
    path: Path,
    errors: list[ValidationMessage],
) -> str:
    value = data.get(key)
    if isinstance(value, str) and value.strip():
        return value.strip()
    errors.append(ValidationMessage(path, f"missing required Codex metadata field: {key}"))
    return ""


def _agent_registration_block(agent: AgentAsset) -> str:
    interface = _mapping(agent.metadata.get("interface"))
    description = _string_value(interface.get("short_description")) or agent.description
    return "\n".join(
        [
            f"[agents.{agent.name}]",
            f'description = "{_toml_escape(description)}"',
            f'config_file = "agents/{_toml_escape(agent.name)}.toml"',
        ]
    )


def normalize_default_prompt(prompt: str, agent: AgentAsset) -> str:
    prefix = f"Use ${agent.name}. "
    if prompt.startswith(prefix):
        return prompt[len(prefix) :]
    return prompt


def _remove_table(text: str, table_name: str) -> str:
    pattern = _table_pattern(table_name)
    match = pattern.search(text)
    if not match:
        return text
    start = match.start()
    next_match = _any_table_pattern().search(text, match.end())
    end = next_match.start() if next_match else len(text)
    before = text[:start].rstrip()
    after = text[end:].lstrip("\n")
    if before and after:
        return before + "\n\n" + after
    return before + after


def _has_table(text: str, table_name: str) -> bool:
    return _table_pattern(table_name).search(text) is not None


def _table_pattern(table_name: str) -> Any:
    return re.compile(rf"(?m)^\[{re.escape(table_name)}\]\s*$")


def _any_table_pattern() -> Any:
    return re.compile(r"(?m)^\[[^\]]+\]\s*$")


def _toml_string_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(f'"{_toml_escape(value)}"' for value in values) + "]"


def wrap_prompt(prompt: str) -> str:
    wrapped_blocks: list[str] = []
    for block in prompt.split("\n\n"):
        lines = block.splitlines()
        if len(lines) > 1 and all(line.startswith(("- ", "  ")) or not line.strip() for line in lines[1:]):
            wrapped_blocks.append("\n".join(_wrap_line(line) for line in lines))
        else:
            wrapped_blocks.append("\n".join(_wrap_line(line) for line in lines))
    return "\n\n".join(wrapped_blocks)


def _wrap_line(line: str) -> str:
    if not line.strip() or len(line) <= PROMPT_WRAP_WIDTH:
        return line
    if line.startswith("- "):
        return textwrap.fill(
            line,
            width=PROMPT_WRAP_WIDTH,
            subsequent_indent="  ",
            break_long_words=False,
            break_on_hyphens=False,
        )
    return textwrap.fill(line, width=PROMPT_WRAP_WIDTH, break_long_words=False, break_on_hyphens=False)


def _toml_escape(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _toml_multiline_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
